### ISSUE TITLE
Appveyor の画面表示が文字化けしている

### ISSUE THREAD

**Issue by sempreff** [TeraTermProject/teraterm#395]
## 概要

Appveyor の履歴ページは
- https://ci.appveyor.com/project/teraterm/github-main/history の方は英語ベースで書かれていて表示に問題ないのですが
- https://ci.appveyor.com/project/teraterm/github-snapshot/history の方は、何がなにやらわかりません。

例えば ttxcheckupdate で snapshot の情報も取り扱おうと思っても、解読できません。( #326 )

## 要望

化けないような内容で記述していただくわけには参りませんでしょうか。

**Comment by nmaya** [comment]
## 現象

たとえば
https://ci.appveyor.com/project/teraterm/github-snapshot/history の
1.0.79 https://ci.appveyor.com/project/teraterm/github-snapshot/builds/51076151 は
branch = 393-local_echo / hash = `7c731e1b` です。

ということは [393-local_echo](https://github.com/TeraTermProject/teraterm/tree/393-local_echo) ブランチの [7c731e1](https://github.com/TeraTermProject/teraterm/commit/7c731e1baf773d47941b6717757b844425db8e67) であり、このコミットメッセージの1行目が `Send file 時 local echo 設定を反映するよう修正 #393` です。

AppVeyor ではこれが文字化けして `Send file æ™‚ local echo è¨­å®šã‚’åæ˜ ã™ã‚‹ã‚ˆã†ä¿®æ­£ #393` と見えています。

## 対策

- 日本語のコミットメッセージでも文字化けしない方法（あるのか？）を探す
- 日本語のコミットメッセージでも文字化けしないよう AppVeyor に要望する
- すべてのコミットメッセージを英語にする

どれが現実的だと思いますか？

**Comment by nmaya** [comment]
コミットの都度、内容を要約した適切な英語表現を考えるのはしんどいです。

ここでは化けていないようです。
https://ci.appveyor.com/project/sakuraeditor/sakura/history
となると、AppVeyor で起動する Windows マシンのロケールあたりが怪しい気がします。

**Comment by zmatsuo** [comment]
> Windows マシンのロケールあたりが怪しい気がします。

AIの出してきた解答の1つが次のものでした。
なんだか当たりな気がします。

AppVeyorのビルド環境でUTF-8を使用するように設定します。具体的には、AppVeyorの設定ファイル（appveyor.yml）に以下のような設定を追加します。

```
environment:
  LANG: ja_JP.UTF-8
```

裏を取ろうと調べていたのですが、まだソースは見つかっていないです。

**Comment by nmaya** [comment]
## LANG 環境変数

```
environment:
  LANG: ja_JP.UTF-8
```

だめでした。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/51076151

これは *NIX 環境での指定の仕方に見えます。

## chcp 

```
init:
  - chcp 65001
```

だめでした。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/51086680

## Set-WinSystemLocale ja-JP

cf. https://matsubara0507.github.io/posts/2018-03-04-fix-tasty-discover-windows.html

```
init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer
```

だめでしたが、今までとは違う化け方になりました。
https://ci.appveyor.com/project/teraterm/github-snapshot/builds/51086759

-----
いったんお手上げです。

-----
注意が必要だと思うことがあります。
ロケールか何かを変更してコミットメッセージが化ないようにできたとして、その調整が「ヘルプファイルのビルド」「ソースのビルド」に影響しない（問題がない）ことを確認しなければなりません。

**Comment by sempreff** [comment]
clone したリポジトリで試してみています。
参考にした手順は https://github.com/TeraTermProject/teraterm/blob/main/ci_scripts/appveyor.md です。
まだビルド終わっていませんが、今のところ化けていない模様です。
https://ci.appveyor.com/project/sempreff/teraterm/history

**Comment by nmaya** [comment]
[Tera Term Project の AppVeyor](https://ci.appveyor.com/account/teraterm/projects) のプロジェクトでは、使う yml をこのように使い分けています。

- github-main
  - appveyor_vs2022_bat.yml
- github-snapshot
  - appveyor_vs2022_bat.yml 
- github-release
  - appveyor_release_bat.yml

github-snapshot, github-main では https://raw.githubusercontent.com/TeraTermProject/teraterm/main/ci_scripts/appveyor_vs2022_bat.yml を使用しています。
AppVeyor ではターゲットとしてブランチを指定しますが、いま main の先端はマージコミットなのでコミットメッセージが日本語ではありません。なので github-snapshot の結果で検証することになりますが、@sempreff さんは bd1a824a をビルドしていて appveyor_vs2022_bat.yml を使っているなら、こちらの使っている yml とは全く差がありません。

もし yml が同一でも文字化けする/しないの違いが起きているとしたら、違うのは AppVeyor のプロジェクトの設定でしょうか？

**Comment by sempreff** [comment]
Settings > General の Custome configuration .yml file name には以下の指定をしています。（yml の内容は変更していません）
```
https://raw.githubusercontent.com/sempreff/teraterm/refs/heads/main/ci_scripts/appveyor_vs2022_bat.yml
```
Settings > Export YAML で表示される内容は以下の通りです。
```
version: 1.0.{build}
branches:
  only:
  - 5.3-stable
image: Visual Studio 2022
build:
  verbosity: minimal
```
Projects の設定のどこかに違いがあるか、Account の設定でしょうか。
Account > Profile で Time zone を `(UTC +09:00) Osaka, Sapporo, Tokyo` に指定した以外は変更していません。

**Comment by nmaya** [comment]
テスト用に[別のプロジェクト](https://ci.appveyor.com/project/teraterm/github-test/history)を作ってみました。

```
プロジェクト設定
Project name: github-test
Project URL slug: github-test
Git repository: https://github.com/sempreff/teraterm.git
Custom configuration .yml file name: https://raw.githubusercontent.com/sempreff/teraterm/refs/heads/main/ci_scripts/appveyor_vs2022_bat.yml
```

```
アカウント設定
Time zone: (UTC+09:00) Osaka, Sapporo, Tokyo
```

タイムゾーンは以前からこうなっています。

-----
@sempreff さんのリポジトリを参照するようにしましたが、文字化けしました。
「yml」「リポジトリ」「アカウント設定」をそろえたつもりですが、どこが違うのか見つからないです。

**Comment by hkanou** [comment]
私の[Appveyor環境](https://ci.appveyor.com/project/hkanou/teratermproject-teraterm/history)も文字化けは起きておりません。
<img width="936" alt="image" src="https://github.com/user-attachments/assets/6c7f2051-7466-4976-b440-6c54030cdc73">
私や sempreff さん環境では、「393-local_echo」、「7c731e1b」のリンク先が表示されますが、TeraTermProject環境では、target="_blank" になっていました。

appveyor の Account と Settings の設定値を下記の場所に格納いたしました。https://github.com/hkanou/ttpmacro/raw/refs/heads/main/tmp/appveyor_settings.zip

> AppVeyor で起動する Windows マシンのロケールあたりが怪しい気がします。

下記のURLを参考に init: に日本語化の設定をしてみましたが、文字化けが起きていない環境のため効果の有無はわかりませんでした。
https://qiita.com/bibou6/items/0a136bca349050d42b20
https://blog.g-gen.co.jp/entry/localize-windows-server-on-gce
```
init:
 - ps: Set-WinCultureFromLanguageListOptOut -OptOut $False
 - ps: Set-WinUserLanguageList -LanguageList ja-JP,en-US -Force
 - ps: Set-TimeZone -Id "Tokyo Standard Time"
 - ps: Set-WinHomeLocation 122
 - ps: Set-WinSystemLocale -SystemLocale ja-JP
 - ps: Set-WinUILanguageOverride -Language ja-JP
 - ps: Start-Sleep -s 10
 - ps: Restart-Computer -Force -Confirm:$false
```
